[package]
name = "mndrp"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "1.6.1"
aws-sdk-bedrockruntime = "1.79.0"
aws-sdk-s3 = "1.81.0"
chrono = "0.4.40"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["macros", "rt"] }
